version: "3.9"
services:
  frontend:
    container_name: frontend
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
    image: "maeddes/hsefrontend:v1"
  backend:
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    image: "maeddes/hsebackend:v1"
  database:
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=matthias
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hsedb
    image: "postgres"